apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "dev-cluster"
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://mboersma.github.io/cluster-api-charts'
    chart: azure-aks-aso
    targetRevision: v0.4.3
    helm:
      valuesObject:
        clusterName: "dev-cluster"
        location: "eastus"
        subscriptionID: "e5a80692-cd9b-4e75-aed6-af99fc79847e"
        clientID: "34d52e1e-998f-4ed2-8733-a96437d4c8ef"
        tenantID: "75f0abaf-9b17-4adc-b5a1-99c0b4e2be66"
        authMode: "workloadidentity"
        kubernetesVersion: v1.32.7
        clusterNetwork: "overlay"
        withClusterClass: true
        withClusterTopology: true
        managedMachinePoolSpecs:
          pool0:
            count: 1
            enableAutoScaling: true
            enableEncryptionAtHost: false
            enableFIPS: false
            enableNodePublicIP: false
            enableUltraSSD: false
            maxCount: 3
            minCount: 1
            mode: System
            osSKU: AzureLinux
            vmSize: Standard_DS2_v2
            type: VirtualMachineScaleSets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
